### ISSUE TITLE
velikost chatovacího okna

### ISSUE THREAD

**Issue by lukas-ther** [snm-chatbot/snm_chatbot_wp_plugin#2]
zvětšit výšku chatovacího okna -> momentálně ve zprávě s gifem není obrázek vidět
<img width="321" alt="screen shot 2017-05-08 at 09 33 49" src="https://cloud.githubusercontent.com/assets/23483910/25794499/7b486b1a-33d1-11e7-83cb-58dd528da4cf.png">

**Comment by crishpeen** [comment]
Fixed
